import './globals.css'
import { Inter } from "next/font/google";

import { createServerComponentClient } from '@supabase/auth-helpers-nextjs';
import { cookies } from 'next/headers';

import AuthProvider from './context/AuthProvider';
import { GlobalContextProvider } from "./context/globalContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const supabase = createServerComponentClient({ cookies });

  const {
    data: { session },
  } = await supabase.auth.getSession();

  return (
    <html lang="en">
      <GlobalContextProvider>
        <body>
          {/*...*/}
          <AuthProvider accessToken={session?.access_token}>{children}</AuthProvider>
          {/*...*/}
        </body>
      </GlobalContextProvider>
    </html>
  );
}